"""add roles profile subscription

Revision ID: 0e2914f31eb5
Revises: 45f18d8620fc
Create Date: 2026-02-15 19:17:38.218266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2914f31eb5'
down_revision: Union[str, None] = '45f18d8620fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'subscriptions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(50), nullable=False, unique=True),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('duration_days', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
    )

    op.create_table(
        'user_roles',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(50), nullable=False, unique=True),
        sa.Column('description', sa.String(255)),
        sa.Column('is_active', sa.Boolean(), nullable=False),
    )

    # Seed default role
    op.execute("""
        INSERT INTO user_roles (name, is_active)
        VALUES ('user', true)
    """)

    op.create_table(
        'user_profiles',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), nullable=False, unique=True),
        sa.Column('full_name', sa.String(100)),
        sa.Column('avatar_url', sa.String(255)),
        sa.Column('phone', sa.String(20)),
        sa.Column('bio', sa.String(255)),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    )

    # Add columns safely
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.add_column(
        'users',
        sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        'users',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False)
    )
    op.add_column(
        'users',
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False)
    )

    # Backfill users
    op.execute("""
        UPDATE users
        SET role_id = (SELECT id FROM user_roles WHERE name = 'user')
    """)

    # Enforce constraints
    op.alter_column('users', 'role_id', nullable=False)
    op.alter_column('users', 'is_verified', server_default=None)

    op.create_foreign_key(
        None, 'users', 'user_roles', ['role_id'], ['id']
    )
    op.create_foreign_key(
        None, 'users', 'subscriptions', ['subscription_id'], ['id']
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'subscription_id')
    op.drop_column('users', 'role_id')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_roles_name'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
